CREATE TABLE `Users` (
  `UserId` INT NOT NULL AUTO_INCREMENT,
  `Username` VARCHAR(255) NOT NULL,
  `PasswordHash` VARCHAR(255) NOT NULL,
  `Email` VARCHAR(255) NOT NULL,
  `Balance` DECIMAL(10, 2) NOT NULL DEFAULT 1000.00
  PRIMARY KEY (`UserId`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE
);

CREATE TABLE `Bets` (
  `BetId` INT NOT NULL AUTO_INCREMENT,
  `UserId` INT NOT NULL,
  `BetAmount` DECIMAL(10, 2) NOT NULL,
  `BetTime` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `Details` VARCHAR(255) NULL,
  PRIMARY KEY (`BetId`),
  INDEX `fk_User_Bet_idx` (`UserId` ASC) VISIBLE,
  CONSTRAINT `fk_User_Bet`
    FOREIGN KEY (`UserId`)
    REFERENCES `Users` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);